//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.13 at 11:48:18 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(
        elementFormDefault= XmlNsForm.QUALIFIED,
        xmlns={
                @XmlNs( prefix = "country",namespaceURI = "http://learn/ws/country-producing-web-service"),
                @XmlNs( prefix = "ticket",namespaceURI = "http://learn/ws/ticket-producing-web-service" )
})
package com.learn.ws.schema;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;