//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 12:23:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        xmlns={
                @XmlNs( prefix = "ticket",namespaceURI = "http://learn/ws/ticket-producing-web-service" )
        })

package com.learn.spring.integration.ws.model;

import javax.xml.bind.annotation.XmlNs;