//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 07:21:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(
        elementFormDefault= XmlNsForm.QUALIFIED,
        xmlns={
                @XmlNs( prefix = "country",namespaceURI = "http://learn/ws/country-producing-web-service"),
        })
package com.learn.ws.client.wsdl;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;